# Generated by Django 3.0.7 on 2020-07-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PseudoApi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=8)),
                ('route', models.CharField(blank=True, max_length=255, null=True)),
                ('body_request', models.TextField()),
                ('body_response', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
