# Generated by Django 3.0.7 on 2020-07-29 19:36

import apifactory.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apifactory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pseudoapi',
            name='body_request',
            field=models.TextField(validators=[apifactory.validators.validate_json]),
        ),
        migrations.AlterField(
            model_name='pseudoapi',
            name='body_response',
            field=models.TextField(validators=[apifactory.validators.validate_json]),
        ),
    ]
