# Generated by Django 3.0.7 on 2020-07-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apifactory', '0002_auto_20200729_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pseudoapi',
            name='route',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
