# Generated by Django 3.0.8 on 2020-07-25 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import workspace.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeApi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('descr', models.TextField(blank=True, null=True)),
                ('method', models.CharField(choices=[('post', 'POST'), ('get', 'GET'), ('delete', 'DELETE'), ('put', 'PUT'), ('patch', 'PATCH'), ('copy', 'COPY'), ('head', 'HEAD'), ('option', 'OPTION')], max_length=10)),
                ('route', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('body_request', workspace.fields.JsonField(default={})),
                ('body_response', workspace.fields.JsonField(default={})),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
