# Generated by Django 3.0.8 on 2020-07-22 22:49

from django.db import migrations
import workspace.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakeapi',
            name='funcs',
            field=workspace.fields.JsonField(default=['random_int', 'random_letter']),
        ),
    ]
